version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx-container
    expose:
      - 80/tcp
    ports:
      - 80:80
    restart: always
    volumes:
      - ./tmp/configs/nginx:/etc/nginx/conf.d:ro
      - ./src:/var/www/wines:ro
    networks:
      - wines-network

  php:
    build:
      context: ./dockerfiles/php
      dockerfile: dockerfile
    container_name: php-container
    restart: always
    volumes:
      - ./src:/var/www/wines
    depends_on:
      - nginx
    networks:
      - wines-network

  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./databases/mysql:/var/lib/mysql
    env_file:
      - mysql.env
    depends_on:
      - nginx
    networks:
      - wines-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8080:80
    restart: always
    env_file:
      - phpmyadmin.env
    depends_on:
      - nginx
      - mysql
    networks:
      - wines-network

networks:
  wines-network:
    name: wines-network
    driver: bridge
